// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SWAPFIT.Data;

#nullable disable

namespace SWAPFIT.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251210072902_anhgiohang")]
    partial class anhgiohang
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SWAPFIT.Model.UserVoucher", b =>
                {
                    b.Property<int>("UserVoucherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserVoucherId"));

                    b.Property<DateTime>("DateClaimed")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VoucherId")
                        .HasColumnType("int");

                    b.HasKey("UserVoucherId");

                    b.HasIndex("UserId");

                    b.HasIndex("VoucherId");

                    b.ToTable("UserVouchers");
                });

            modelBuilder.Entity("SWAPFIT.Models.AnhBaiViet", b =>
                {
                    b.Property<int>("MaAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaAnh"));

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaBaiViet")
                        .HasColumnType("int");

                    b.HasKey("MaAnh");

                    b.HasIndex("MaBaiViet");

                    b.ToTable("AnhBaiViets");
                });

            modelBuilder.Entity("SWAPFIT.Models.BaiViet", b =>
                {
                    b.Property<int>("MaBaiViet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBaiViet"));

                    b.Property<decimal?>("GiaSanPham")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoaiBaiDang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LyDo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaDanhMuc")
                        .HasColumnType("int");

                    b.Property<int?>("MaDiaChi")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int?>("MaThuongHieu")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiDungMaNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Size")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaBaiViet");

                    b.HasIndex("MaDanhMuc");

                    b.HasIndex("MaDiaChi");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaThuongHieu");

                    b.HasIndex("NguoiDungMaNguoiDung");

                    b.ToTable("BaiViets");
                });

            modelBuilder.Entity("SWAPFIT.Models.BaoCao", b =>
                {
                    b.Property<int>("MaBaoCao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBaoCao"));

                    b.Property<string>("ChiTiet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LyDo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaDoCu")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiBaoCao")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaBaoCao");

                    b.ToTable("BaoCaos");
                });

            modelBuilder.Entity("SWAPFIT.Models.BaoCaoTaiKhoan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LyDo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaNguoiBaoCao")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiBiBaoCao")
                        .HasColumnType("int");

                    b.Property<string>("MoTaChiTiet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaNguoiBaoCao");

                    b.HasIndex("MaNguoiBiBaoCao");

                    b.ToTable("BaoCaoTaiKhoans");
                });

            modelBuilder.Entity("SWAPFIT.Models.BaoCaoTaiKhoanAnh", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BaoCaoTaiKhoanId")
                        .HasColumnType("int");

                    b.Property<int?>("BaoCaoTaiKhoanId1")
                        .HasColumnType("int");

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BaoCaoTaiKhoanId");

                    b.HasIndex("BaoCaoTaiKhoanId1");

                    b.ToTable("BaoCaoTaiKhoanAnhs");
                });

            modelBuilder.Entity("SWAPFIT.Models.BinhLuanTinTuc", b =>
                {
                    b.Property<int>("MaBinhLuan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaBinhLuan"));

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int>("MaTinTuc")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayBinhLuan")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("MaBinhLuan");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("ParentId");

                    b.ToTable("BinhLuanTinTucs");
                });

            modelBuilder.Entity("SWAPFIT.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("MaChiTietDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTietDonHang"));

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaBaiViet")
                        .HasColumnType("int");

                    b.Property<int>("MaDonHang")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaChiTietDonHang");

                    b.HasIndex("MaBaiViet");

                    b.HasIndex("MaDonHang");

                    b.ToTable("ChiTietDonHangs");
                });

            modelBuilder.Entity("SWAPFIT.Models.ChiTietGioHang", b =>
                {
                    b.Property<int>("MaChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTiet"));

                    b.Property<string>("AnhSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaBaiViet")
                        .HasColumnType("int");

                    b.Property<int>("MaGioHang")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("MaChiTiet");

                    b.HasIndex("MaBaiViet");

                    b.HasIndex("MaGioHang");

                    b.ToTable("ChiTietGioHangs");
                });

            modelBuilder.Entity("SWAPFIT.Models.DanhGia", b =>
                {
                    b.Property<int>("MaDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhGia"));

                    b.Property<string>("BinhLuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Diem")
                        .HasColumnType("int");

                    b.Property<int>("MaDoCu")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayDanhGia")
                        .HasColumnType("datetime2");

                    b.HasKey("MaDanhGia");

                    b.ToTable("DanhGias");
                });

            modelBuilder.Entity("SWAPFIT.Models.DanhMuc", b =>
                {
                    b.Property<int>("MaDanhMuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDanhMuc"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaDanhMuc");

                    b.ToTable("DanhMucs");
                });

            modelBuilder.Entity("SWAPFIT.Models.DiaChi", b =>
                {
                    b.Property<int>("MaDiaChi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDiaChi"));

                    b.Property<string>("ChiTiet")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Huyen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LaMacDinh")
                        .HasColumnType("bit");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("Tinh")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Xa")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaDiaChi");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("DiaChis");
                });

            modelBuilder.Entity("SWAPFIT.Models.DoCu", b =>
                {
                    b.Property<int>("MaDoCu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDoCu"));

                    b.Property<string>("AnhSanPham")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("DiaChiId")
                        .HasColumnType("int");

                    b.Property<decimal?>("GiaTriUocTinh")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LoaiBaiDang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaDanhMuc")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int?>("MaThuongHieu")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayDang")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhuongThucTraoDoi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Size")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenSanPham")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TinhTrang")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDoCu");

                    b.HasIndex("MaDanhMuc");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("MaThuongHieu");

                    b.ToTable("DoCus");
                });

            modelBuilder.Entity("SWAPFIT.Models.DonHang", b =>
                {
                    b.Property<int>("MaDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDonHang"));

                    b.Property<string>("DiaChiGiaoHang")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("MaNguoiBan")
                        .HasColumnType("int");

                    b.Property<int?>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int?>("MaNguoiMua")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiDungMaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiDungMaNguoiDung1")
                        .HasColumnType("int");

                    b.Property<string>("PhuongThucGiaoHang")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhuongThucThanhToan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TaiKhoan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDonHang");

                    b.HasIndex("MaNguoiBan");

                    b.HasIndex("MaNguoiMua");

                    b.HasIndex("NguoiDungMaNguoiDung");

                    b.HasIndex("NguoiDungMaNguoiDung1");

                    b.ToTable("DonHangs");
                });

            modelBuilder.Entity("SWAPFIT.Models.GiaoDich", b =>
                {
                    b.Property<int>("MaGiaoDich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGiaoDich"));

                    b.Property<decimal?>("GiaTri")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaYeuCau")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayGiaoDich")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaGiaoDich");

                    b.ToTable("GiaoDichs");
                });

            modelBuilder.Entity("SWAPFIT.Models.GioHang", b =>
                {
                    b.Property<int>("MaGioHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGioHang"));

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayCapNhat")
                        .HasColumnType("datetime2");

                    b.HasKey("MaGioHang");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("GioHangs");
                });

            modelBuilder.Entity("SWAPFIT.Models.HinhAnh", b =>
                {
                    b.Property<int>("MaHinhAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHinhAnh"));

                    b.Property<string>("DuongDan")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaDoCu")
                        .HasColumnType("int");

                    b.HasKey("MaHinhAnh");

                    b.ToTable("HinhAnhs");
                });

            modelBuilder.Entity("SWAPFIT.Models.HoTro", b =>
                {
                    b.Property<int>("MaHoTro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoTro"));

                    b.Property<string>("ChuDe")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayGui")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaHoTro");

                    b.ToTable("HoTros");
                });

            modelBuilder.Entity("SWAPFIT.Models.LichSuDangNhap", b =>
                {
                    b.Property<int>("MaLichSu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLichSu"));

                    b.Property<string>("DiaChiIP")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGianDangNhap")
                        .HasColumnType("datetime2");

                    b.HasKey("MaLichSu");

                    b.ToTable("LichSuDangNhaps");
                });

            modelBuilder.Entity("SWAPFIT.Models.LuotTimKiem", b =>
                {
                    b.Property<int>("MaTimKiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTimKiem"));

                    b.Property<DateTime?>("LanCuoiTim")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SoLanTim")
                        .HasColumnType("int");

                    b.Property<string>("TuKhoa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaTimKiem");

                    b.ToTable("LuotTimKiems");
                });

            modelBuilder.Entity("SWAPFIT.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("AnhDaiDien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaiTro")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaNguoiDung");

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("SWAPFIT.Models.NhatKyHeThong", b =>
                {
                    b.Property<int>("MaNhatKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNhatKy"));

                    b.Property<string>("HanhDong")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.Property<string>("ThucHienBoi")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaNhatKy");

                    b.ToTable("NhatKyHeThongs");
                });

            modelBuilder.Entity("SWAPFIT.Models.PhanHoiHoTro", b =>
                {
                    b.Property<int>("MaPhanHoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhanHoi"));

                    b.Property<int>("MaHoTro")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayPhanHoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaPhanHoi");

                    b.ToTable("PhanHoiHoTros");
                });

            modelBuilder.Entity("SWAPFIT.Models.TheLoaiTinTuc", b =>
                {
                    b.Property<int>("MaTheLoai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTheLoai"));

                    b.Property<string>("TenTheLoai")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaTheLoai");

                    b.ToTable("TheLoaiTinTucs");
                });

            modelBuilder.Entity("SWAPFIT.Models.ThongBao", b =>
                {
                    b.Property<int>("MaThongBao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThongBao"));

                    b.Property<bool>("DaXem")
                        .HasColumnType("bit");

                    b.Property<string>("LienKet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoaiThongBao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaThongBao");

                    b.ToTable("ThongBaos");
                });

            modelBuilder.Entity("SWAPFIT.Models.ThongKe", b =>
                {
                    b.Property<int>("MaThongKe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThongKe"));

                    b.Property<DateTime?>("NgayThongKe")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TongBaiViet")
                        .HasColumnType("int");

                    b.Property<int?>("TongGiaoDich")
                        .HasColumnType("int");

                    b.Property<int?>("TongNguoiDung")
                        .HasColumnType("int");

                    b.HasKey("MaThongKe");

                    b.ToTable("ThongKes");
                });

            modelBuilder.Entity("SWAPFIT.Models.ThuongHieu", b =>
                {
                    b.Property<int>("MaThuongHieu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaThuongHieu"));

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenThuongHieu")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaThuongHieu");

                    b.ToTable("ThuongHieus");
                });

            modelBuilder.Entity("SWAPFIT.Models.TinNhan", b =>
                {
                    b.Property<int>("MaTinNhan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTinNhan"));

                    b.Property<bool?>("DaDoc")
                        .HasColumnType("bit");

                    b.Property<int>("MaNguoiGui")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiNhan")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiGuiMaNguoiDung")
                        .HasColumnType("int");

                    b.Property<int?>("NguoiNhanMaNguoiDung")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ThoiGianGui")
                        .HasColumnType("datetime2");

                    b.HasKey("MaTinNhan");

                    b.HasIndex("MaNguoiGui");

                    b.HasIndex("MaNguoiNhan");

                    b.HasIndex("NguoiGuiMaNguoiDung");

                    b.HasIndex("NguoiNhanMaNguoiDung");

                    b.ToTable("TinNhans");
                });

            modelBuilder.Entity("SWAPFIT.Models.TinTuc", b =>
                {
                    b.Property<int>("MaTinTuc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTinTuc"));

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KichThuoc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LoaiSanPham")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaTheLoai")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayDang")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaTinTuc");

                    b.ToTable("TinTucs");
                });

            modelBuilder.Entity("SWAPFIT.Models.UuDai", b =>
                {
                    b.Property<int>("MaUuDai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaUuDai"));

                    b.Property<string>("AnhBia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("GiaTri")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("GioiHanSoLuong")
                        .HasColumnType("int");

                    b.Property<string>("LoaiUuDai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenUuDai")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("MaUuDai");

                    b.ToTable("UuDais");
                });

            modelBuilder.Entity("SWAPFIT.Models.UuDaiSanPham", b =>
                {
                    b.Property<int>("MaUuDaiSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaUuDaiSanPham"));

                    b.Property<int>("MaDoCu")
                        .HasColumnType("int");

                    b.Property<int>("MaUuDai")
                        .HasColumnType("int");

                    b.HasKey("MaUuDaiSanPham");

                    b.HasIndex("MaDoCu");

                    b.HasIndex("MaUuDai");

                    b.ToTable("UuDaiSanPhams");
                });

            modelBuilder.Entity("SWAPFIT.Models.YeuCau", b =>
                {
                    b.Property<int>("MaYeuCau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaYeuCau"));

                    b.Property<int?>("MaDoCu")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayGui")
                        .HasColumnType("datetime2");

                    b.Property<int>("NguoiGuiId")
                        .HasColumnType("int");

                    b.Property<int>("NguoiNhanId")
                        .HasColumnType("int");

                    b.Property<string>("NoiDung")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaYeuCau");

                    b.HasIndex("NguoiGuiId");

                    b.HasIndex("NguoiNhanId");

                    b.ToTable("YeuCaus");
                });

            modelBuilder.Entity("SWAPFIT.Models.YeuThich", b =>
                {
                    b.Property<int>("MaYeuThich")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaYeuThich"));

                    b.Property<int>("MaDoCu")
                        .HasColumnType("int");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int");

                    b.HasKey("MaYeuThich");

                    b.ToTable("YeuThichs");
                });

            modelBuilder.Entity("SWAPFIT.Model.UserVoucher", b =>
                {
                    b.HasOne("SWAPFIT.Models.NguoiDung", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWAPFIT.Models.UuDai", "Voucher")
                        .WithMany()
                        .HasForeignKey("VoucherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Voucher");
                });

            modelBuilder.Entity("SWAPFIT.Models.AnhBaiViet", b =>
                {
                    b.HasOne("SWAPFIT.Models.BaiViet", "BaiViet")
                        .WithMany("AnhBaiViets")
                        .HasForeignKey("MaBaiViet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaiViet");
                });

            modelBuilder.Entity("SWAPFIT.Models.BaiViet", b =>
                {
                    b.HasOne("SWAPFIT.Models.DanhMuc", "DanhMuc")
                        .WithMany()
                        .HasForeignKey("MaDanhMuc");

                    b.HasOne("SWAPFIT.Models.DiaChi", "DiaChi")
                        .WithMany()
                        .HasForeignKey("MaDiaChi");

                    b.HasOne("SWAPFIT.Models.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWAPFIT.Models.ThuongHieu", "ThuongHieu")
                        .WithMany()
                        .HasForeignKey("MaThuongHieu");

                    b.HasOne("SWAPFIT.Models.NguoiDung", "NguoiDung")
                        .WithMany("BaiViets")
                        .HasForeignKey("NguoiDungMaNguoiDung");

                    b.Navigation("DanhMuc");

                    b.Navigation("DiaChi");

                    b.Navigation("NguoiDung");

                    b.Navigation("ThuongHieu");
                });

            modelBuilder.Entity("SWAPFIT.Models.BaoCaoTaiKhoan", b =>
                {
                    b.HasOne("SWAPFIT.Models.NguoiDung", "NguoiBaoCao")
                        .WithMany()
                        .HasForeignKey("MaNguoiBaoCao")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SWAPFIT.Models.NguoiDung", "NguoiBiBaoCao")
                        .WithMany()
                        .HasForeignKey("MaNguoiBiBaoCao")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("NguoiBaoCao");

                    b.Navigation("NguoiBiBaoCao");
                });

            modelBuilder.Entity("SWAPFIT.Models.BaoCaoTaiKhoanAnh", b =>
                {
                    b.HasOne("SWAPFIT.Models.BaoCaoTaiKhoan", "BaoCaoTaiKhoan")
                        .WithMany()
                        .HasForeignKey("BaoCaoTaiKhoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWAPFIT.Models.BaoCaoTaiKhoan", null)
                        .WithMany("BaoCaoTaiKhoanAnhs")
                        .HasForeignKey("BaoCaoTaiKhoanId1");

                    b.Navigation("BaoCaoTaiKhoan");
                });

            modelBuilder.Entity("SWAPFIT.Models.BinhLuanTinTuc", b =>
                {
                    b.HasOne("SWAPFIT.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWAPFIT.Models.BinhLuanTinTuc", "Parent")
                        .WithMany("Replies")
                        .HasForeignKey("ParentId");

                    b.Navigation("NguoiDung");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SWAPFIT.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("SWAPFIT.Models.BaiViet", "BaiViet")
                        .WithMany()
                        .HasForeignKey("MaBaiViet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWAPFIT.Models.DonHang", "DonHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("MaDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaiViet");

                    b.Navigation("DonHang");
                });

            modelBuilder.Entity("SWAPFIT.Models.ChiTietGioHang", b =>
                {
                    b.HasOne("SWAPFIT.Models.BaiViet", "BaiViet")
                        .WithMany()
                        .HasForeignKey("MaBaiViet")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SWAPFIT.Models.GioHang", "GioHang")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaGioHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BaiViet");

                    b.Navigation("GioHang");
                });

            modelBuilder.Entity("SWAPFIT.Models.DiaChi", b =>
                {
                    b.HasOne("SWAPFIT.Models.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SWAPFIT.Models.DoCu", b =>
                {
                    b.HasOne("SWAPFIT.Models.DanhMuc", null)
                        .WithMany()
                        .HasForeignKey("MaDanhMuc")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SWAPFIT.Models.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWAPFIT.Models.ThuongHieu", null)
                        .WithMany()
                        .HasForeignKey("MaThuongHieu")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("SWAPFIT.Models.DonHang", b =>
                {
                    b.HasOne("SWAPFIT.Models.NguoiDung", "NguoiBan")
                        .WithMany()
                        .HasForeignKey("MaNguoiBan")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SWAPFIT.Models.NguoiDung", "NguoiMua")
                        .WithMany()
                        .HasForeignKey("MaNguoiMua")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SWAPFIT.Models.NguoiDung", null)
                        .WithMany("DonBan")
                        .HasForeignKey("NguoiDungMaNguoiDung");

                    b.HasOne("SWAPFIT.Models.NguoiDung", null)
                        .WithMany("DonMua")
                        .HasForeignKey("NguoiDungMaNguoiDung1");

                    b.Navigation("NguoiBan");

                    b.Navigation("NguoiMua");
                });

            modelBuilder.Entity("SWAPFIT.Models.GioHang", b =>
                {
                    b.HasOne("SWAPFIT.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("SWAPFIT.Models.TinNhan", b =>
                {
                    b.HasOne("SWAPFIT.Models.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("MaNguoiGui")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SWAPFIT.Models.NguoiDung", null)
                        .WithMany()
                        .HasForeignKey("MaNguoiNhan")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("SWAPFIT.Models.NguoiDung", "NguoiGui")
                        .WithMany()
                        .HasForeignKey("NguoiGuiMaNguoiDung");

                    b.HasOne("SWAPFIT.Models.NguoiDung", "NguoiNhan")
                        .WithMany()
                        .HasForeignKey("NguoiNhanMaNguoiDung");

                    b.Navigation("NguoiGui");

                    b.Navigation("NguoiNhan");
                });

            modelBuilder.Entity("SWAPFIT.Models.UuDaiSanPham", b =>
                {
                    b.HasOne("SWAPFIT.Models.DoCu", "DoCu")
                        .WithMany()
                        .HasForeignKey("MaDoCu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SWAPFIT.Models.UuDai", "UuDai")
                        .WithMany()
                        .HasForeignKey("MaUuDai")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DoCu");

                    b.Navigation("UuDai");
                });

            modelBuilder.Entity("SWAPFIT.Models.YeuCau", b =>
                {
                    b.HasOne("SWAPFIT.Models.NguoiDung", "NguoiGui")
                        .WithMany()
                        .HasForeignKey("NguoiGuiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SWAPFIT.Models.NguoiDung", "NguoiNhan")
                        .WithMany()
                        .HasForeignKey("NguoiNhanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NguoiGui");

                    b.Navigation("NguoiNhan");
                });

            modelBuilder.Entity("SWAPFIT.Models.BaiViet", b =>
                {
                    b.Navigation("AnhBaiViets");
                });

            modelBuilder.Entity("SWAPFIT.Models.BaoCaoTaiKhoan", b =>
                {
                    b.Navigation("BaoCaoTaiKhoanAnhs");
                });

            modelBuilder.Entity("SWAPFIT.Models.BinhLuanTinTuc", b =>
                {
                    b.Navigation("Replies");
                });

            modelBuilder.Entity("SWAPFIT.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");
                });

            modelBuilder.Entity("SWAPFIT.Models.GioHang", b =>
                {
                    b.Navigation("ChiTietGioHangs");
                });

            modelBuilder.Entity("SWAPFIT.Models.NguoiDung", b =>
                {
                    b.Navigation("BaiViets");

                    b.Navigation("DonBan");

                    b.Navigation("DonMua");
                });
#pragma warning restore 612, 618
        }
    }
}
